// 파일 경로: src/features/line-dashboard/utils/dataTableColumnConfig.js
// 컬럼 기본 동작(순서/라벨/정렬/기본 너비 등)을 한 곳에 모아둔 객체입니다.
export const DEFAULT_CONFIG = {
  order: [
    "created_at",
    "line_id",
    "sdwt_prod",
    "user_sdwt_prod",
    "sample_type",
    "sample_group",
    "proc_id",
    "ppid",
    "EQP_CB",
    "lot_id",
    "status",
    "process_flow",
    "comment",
    "instant_inform",
    "needtosend",
    "knox_id",
    "delivery_targets",
    "delivery_status",
    "informed_at",
    "jira_key",
    "ctttm_urls",
    "defect_url",
  ],
  labels: {
    ctttm_urls: "CTTTM",
    defect_url: "Defect",
    jira_key: "Jira",
    comment: "Comment",
    instant_inform: "즉시인폼",
    needtosend: "예약",
    delivery_status: "전송 상태",
    delivery_jira: "Jira",
    delivery_messenger: "Teams",
    delivery_mail: "Mail",
    informed_at: "최근 성공시각",
    status: "Status",
    knox_id: "KnoxID",
    process_flow: "Process Flow",
    delivery_targets: "알림 Target",
    user_sdwt_prod: "User 분임조",
    sdwt_prod: "설비 분임조",
  },
  sortable: {
    ctttm_urls: false,
    defect_url: false,
    jira_key: false,
    comment: true,
    instant_inform: true,
    needtosend: true,
    delivery_status: true,
    delivery_jira: true,
    delivery_messenger: true,
    delivery_mail: true,
    informed_at: true,
    status: true,
  },
  sortTypes: {
    comment: "text",
    instant_inform: "number",
    needtosend: "number",
    delivery_status: "number",
    delivery_jira: "number",
    delivery_messenger: "number",
    delivery_mail: "number",
    informed_at: "datetime",
    status: "text",
  },
  width: {
    created_at: 100,
    line_id: 60,
    sdwt_prod: 120,
    EQP_CB: 110,
    proc_id: 60,
    ppid: 120,
    sample_type: 180,
    sample_group: 150,
    lot_id: 100,
    status: 150,
    delivery_targets: 150,
    delivery_status: 280,
    process_flow: 450,
    comment: 250,
    instant_inform: 60,
    needtosend: 40,
    delivery_jira: 92,
    delivery_messenger: 100,
    delivery_mail: 92,
    informed_at: 100,
    jira_key: 40,
    ctttm_urls: 60,
    defect_url: 60,
    knox_id: 100,
    user_sdwt_prod: 120,
    updated_at: 100,
  },
  processFlowHeader: "process_flow",
  cellAlign: {
    created_at: "center",
    line_id: "center",
    sdwt_prod: "center",
    delivery_targets: "center",
    delivery_status: "center",
    EQP_CB: "left",
    proc_id: "center",
    ppid: "left",
    sample_type: "left",
    sample_group: "left",
    lot_id: "center",
    status: "center",
    process_flow: "left",
    comment: "left",
    instant_inform: "center",
    needtosend: "center",
    delivery_jira: "center",
    delivery_messenger: "center",
    delivery_mail: "center",
    informed_at: "center",
    jira_key: "center",
    ctttm_urls: "center",
    defect_url: "center",
    knox_id: "center",
    user_sdwt_prod: "center",
  },
  headerAlign: {
    created_at: "center",
    line_id: "center",
    sdwt_prod: "center",
    delivery_targets: "center",
    delivery_status: "center",
    EQP_CB: "left",
    proc_id: "center",
    ppid: "center",
    sample_type: "center",
    sample_group: "center",
    lot_id: "center",
    status: "center",
    process_flow: "left",
    comment: "left",
    instant_inform: "center",
    needtosend: "center",
    delivery_jira: "center",
    delivery_messenger: "center",
    delivery_mail: "center",
    informed_at: "center",
    jira_key: "center",
    ctttm_urls: "center",
    defect_url: "center",
    knox_id: "center",
    user_sdwt_prod: "center",
  },
}

// 사용자가 전달한 설정을 기본값과 합쳐 안전하게 반환합니다.
export function mergeConfig(userConfig) {
  const overrides = userConfig ?? {}
  return {
    order: overrides.order ?? DEFAULT_CONFIG.order,
    labels: { ...DEFAULT_CONFIG.labels, ...(overrides.labels ?? {}) },
    sortable: { ...DEFAULT_CONFIG.sortable, ...(overrides.sortable ?? {}) },
    sortTypes: { ...DEFAULT_CONFIG.sortTypes, ...(overrides.sortTypes ?? {}) },
    width: { ...DEFAULT_CONFIG.width, ...(overrides.width ?? {}) },
    processFlowHeader: overrides.processFlowHeader ?? DEFAULT_CONFIG.processFlowHeader,
    cellAlign: { ...DEFAULT_CONFIG.cellAlign, ...(overrides.cellAlign ?? {}) },
    headerAlign: { ...DEFAULT_CONFIG.headerAlign, ...(overrides.headerAlign ?? {}) },
  }
}
