apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailwind-local
resources:
  - ../../../../deploy/portal/k8s/jobs/migrate
images:
  - name: portal-api
    newName: tailwind-api
    newTag: k8s-local
patches:
  - path: job-local-patch.yaml
