# Generated by Codex on 2026-06-20

from __future__ import annotations

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MiTipUpdateHist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tip_event_key", models.CharField(max_length=32)),
                ("line_id", models.CharField(blank=True, max_length=10, null=True)),
                ("eqp_cb", models.CharField(max_length=65)),
                ("step_seq", models.CharField(blank=True, max_length=16, null=True)),
                ("process_id", models.CharField(blank=True, max_length=16, null=True)),
                ("ppid", models.CharField(blank=True, max_length=40, null=True)),
                ("reticle_id", models.CharField(blank=True, max_length=30, null=True)),
                ("product_id", models.CharField(blank=True, max_length=40, null=True)),
                ("sum_time", models.CharField(blank=True, max_length=15, null=True)),
                ("rule_pkg_update_date", models.DateTimeField(blank=True, null=True)),
                ("gpm_update_date", models.DateTimeField()),
                ("register_name", models.CharField(blank=True, max_length=40, null=True)),
                ("event_type", models.CharField(blank=True, max_length=40, null=True)),
                ("tip_type", models.CharField(blank=True, max_length=40, null=True)),
                ("tip_chg_type", models.CharField(blank=True, max_length=40, null=True)),
                ("tip_level", models.CharField(blank=True, max_length=16, null=True)),
                ("tip_comment", models.CharField(blank=True, max_length=255, null=True)),
                ("tkin_restrc_lot_count", models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ("cur_tkin_lot_count", models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ("term_intlk_occur_time", models.CharField(blank=True, max_length=18, null=True)),
                ("last_update_date", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
            ],
            options={
                "db_table": "mi_tip_update_hist",
                "indexes": [
                    models.Index(fields=["eqp_cb", "gpm_update_date"], name="idx_mi_tip_upd_hist_cb_dt"),
                    models.Index(fields=["gpm_update_date"], name="idx_mi_tip_upd_hist_dt"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tip_event_key",), name="uniq_mi_tip_upd_hist_evt"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MiTipUpdateHistLoadJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.TextField()),
                ("file_path", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("dry_run", "Dry run"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
            ],
            options={
                "db_table": "mi_tip_update_hist_load_job",
                "indexes": [
                    models.Index(fields=["status"], name="idx_mi_tip_upd_hist_lj_sts"),
                    models.Index(fields=["created_at"], name="idx_mi_tip_upd_hist_lj_crt"),
                ],
            },
        ),
    ]
