apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailwind-internal
resources:
  - ../../../jobs/migrate
images:
  - name: portal-api
    newName: registry.internal.example.invalid/tailwind/api
    newTag: replace-me
