include:
  - path: compose/prod.infra.yml
    env_file: env/work-hub.prod.env
  - path: compose/prod.app.yml
    env_file: env/work-hub.prod.env
  - path: compose/prod.work-hub.yml
    env_file: env/work-hub.prod.env
