# Generated by Django 5.2.9 on 2025-12-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('received_at', models.DateTimeField()),
                ('subject', models.TextField()),
                ('sender', models.TextField()),
                ('sender_id', models.CharField(db_index=True, max_length=50)),
                ('recipient', models.TextField()),
                ('user_sdwt_prod', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_html_gzip', models.BinaryField(blank=True, null=True)),
                ('rag_doc_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emails_inbox',
            },
        ),
    ]
