# Generated by GPT-5.2 on 2025-12-15

from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name="email",
            name="cc",
            field=ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name="email",
            name="participants_search",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE emails_inbox "
                        "ALTER COLUMN recipient TYPE text[] "
                        "USING CASE "
                        "WHEN recipient IS NULL THEN NULL "
                        "ELSE ARRAY[recipient] "
                        "END;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE emails_inbox "
                        "ALTER COLUMN recipient TYPE text "
                        "USING CASE "
                        "WHEN recipient IS NULL THEN NULL "
                        "ELSE recipient[1] "
                        "END;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="email",
                    name="recipient",
                    field=ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="email",
            index=GinIndex(fields=["recipient"], name="idx_emails_inbox_recipient_gin"),
        ),
        migrations.AddIndex(
            model_name="email",
            index=GinIndex(fields=["cc"], name="idx_emails_inbox_cc_gin"),
        ),
        migrations.AddIndex(
            model_name="email",
            index=GinIndex(
                fields=["participants_search"],
                name="idx_emails_inbox_part_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
