# Generated by Django 5.2.7 on 2026-08-18

from django.db import migrations


def validate_single_app_value(apps, schema_editor):
    """제거 전에 VOC 앱 값이 기존 단일 계약 안에 있는지 확인합니다."""

    VocPost = apps.get_model("voc", "VocPost")
    unexpected_values = sorted(
        value
        for value in VocPost.objects.values_list("app", flat=True).distinct()
        if value not in {"", "기타"}
    )
    if unexpected_values:
        raise RuntimeError(
            "voc_post.app에 제거할 수 없는 값이 있습니다: "
            + ", ".join(unexpected_values)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("voc", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            validate_single_app_value,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="vocpost",
            name="app",
        ),
    ]
