# Generated by Django 5.2.7 on 2025-12-13 06:21

import django.db.models.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drone", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dronesopv3",
            name="send_jira",
            field=models.SmallIntegerField(blank=True, db_default=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="dronesopv3",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.Now()),
        ),
        migrations.AlterField(
            model_name="dronesopv3",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.Now()),
        ),
    ]
