# Generated by Django 5.2.9 on 2025-12-18

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drone", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DroneEarlyInformV3",
            new_name="DroneEarlyInform",
        ),
        migrations.RenameModel(
            old_name="DroneSOPV3",
            new_name="DroneSOP",
        ),
        migrations.AlterModelTable(
            name="droneearlyinform",
            table="drone_early_inform",
        ),
        migrations.AlterModelTable(
            name="dronesop",
            table="drone_sop",
        ),
        migrations.RenameIndex(
            model_name="dronesop",
            old_name="drone_sop_v3_created_at_id",
            new_name="drone_sop_created_at_id",
        ),
        migrations.RenameIndex(
            model_name="dronesop",
            old_name="dsopv3_usr_sdwt_created_id",
            new_name="dsop_usr_sdwt_created_id",
        ),
        migrations.RenameIndex(
            model_name="dronesop",
            old_name="drone_sop_v3_send_jira",
            new_name="drone_sop_send_jira",
        ),
        migrations.RenameIndex(
            model_name="dronesop",
            old_name="drone_sop_v3_knoxid",
            new_name="drone_sop_knoxid",
        ),
    ]

