# Generated by Django 5.2.9 on 2025-12-18

from __future__ import annotations

from django.db import migrations, models
from django.db.models.functions import Now


class Migration(migrations.Migration):

    dependencies = [
        ("drone", "0002_remove_v3"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroneSopJiraTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_id", models.CharField(max_length=50, unique=True)),
                ("template_key", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_default=Now())),
                ("updated_at", models.DateTimeField(auto_now=True, db_default=Now())),
            ],
            options={
                "db_table": "drone_sop_jira_template",
            },
        ),
        migrations.AddIndex(
            model_name="dronesopjiratemplate",
            index=models.Index(fields=["line_id"], name="drone_jira_tpl_line"),
        ),
    ]
