# Generated by Django 5.2.9 on 2025-12-19

from __future__ import annotations

from django.db import migrations, models
from django.db.models.functions import Now


class Migration(migrations.Migration):

    dependencies = [
        ("drone", "0003_drone_sop_jira_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroneSopJiraUserTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_sdwt_prod", models.CharField(max_length=50, unique=True)),
                ("template_key", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_default=Now())),
                ("updated_at", models.DateTimeField(auto_now=True, db_default=Now())),
            ],
            options={
                "db_table": "drone_sop_jira_user_template",
            },
        ),
        migrations.AddIndex(
            model_name="dronesopjirausertemplate",
            index=models.Index(fields=["user_sdwt_prod"], name="drone_jira_tpl_user"),
        ),
    ]
