// src/features/line-dashboard/utils/dataTableColumnConfig.js
// 컬럼 기본 동작(순서/라벨/정렬/기본 너비 등)을 한 곳에 모아둔 객체입니다.
export const DEFAULT_CONFIG = {
  order: [
    "created_at",
    "line_id",
    "sdwt_prod",
    "EQP_CB",
    "proc_id",
    "ppid",
    "sample_type",
    "sample_group",
    "lot_id",
    "status",
    "process_flow",
    "comment",
    "instant_inform",
    "needtosend",
    "send_jira",
    "informed_at",
    "jira_key",
    "defect_url",
    "knoxid",
    "user_sdwt_prod",
  ],
  labels: {
    defect_url: "Defect",
    jira_key: "Jira",
    comment: "Comment",
    instant_inform: "즉시인폼",
    needtosend: "예약",
    send_jira: "JIRA",
    status: "Status",
    knoxid: "KnoxID",
    process_flow: "Process Flow",
  },
  sortable: {
    defect_url: false,
    jira_key: false,
    comment: true,
    instant_inform: true,
    needtosend: true,
    send_jira: true,
    status: true,
  },
  sortTypes: {
    comment: "text",
    instant_inform: "number",
    needtosend: "number",
    send_jira: "number",
    status: "text",
  },
  width: {
    created_at: 100,
    line_id: 60,
    sdwt_prod: 120,
    EQP_CB: 110,
    proc_id: 60,
    ppid: 120,
    sample_type: 180,
    sample_group: 150,
    lot_id: 100,
    status: 150,
    process_flow: 450,
    comment: 250,
    instant_inform: 60,
    needtosend: 40,
    send_jira: 40,
    informed_at: 100,
    jira_key: 40,
    defect_url: 60,
    knoxid: 100,
    user_sdwt_prod: 120,
    updated_at: 100,
  },
  processFlowHeader: "process_flow",
  cellAlign: {
    created_at: "center",
    line_id: "center",
    sdwt_prod: "center",
    EQP_CB: "left",
    proc_id: "center",
    ppid: "left",
    sample_type: "left",
    sample_group: "left",
    lot_id: "center",
    status: "center",
    process_flow: "left",
    comment: "left",
    instant_inform: "center",
    needtosend: "center",
    send_jira: "center",
    informed_at: "center",
    jira_key: "center",
    defect_url: "center",
    knoxid: "center",
    user_sdwt_prod: "center",
  },
  headerAlign: {
    created_at: "center",
    line_id: "center",
    sdwt_prod: "center",
    EQP_CB: "left",
    proc_id: "center",
    ppid: "center",
    sample_type: "center",
    sample_group: "center",
    lot_id: "center",
    status: "center",
    process_flow: "left",
    comment: "left",
    instant_inform: "center",
    needtosend: "center",
    send_jira: "center",
    informed_at: "center",
    jira_key: "center",
    defect_url: "center",
    knoxid: "center",
    user_sdwt_prod: "center",
  },
}

// 사용자가 전달한 설정을 기본값과 합쳐 안전하게 반환합니다.
export function mergeConfig(userConfig) {
  const overrides = userConfig ?? {}
  return {
    order: overrides.order ?? DEFAULT_CONFIG.order,
    labels: { ...DEFAULT_CONFIG.labels, ...(overrides.labels ?? {}) },
    sortable: { ...DEFAULT_CONFIG.sortable, ...(overrides.sortable ?? {}) },
    sortTypes: { ...DEFAULT_CONFIG.sortTypes, ...(overrides.sortTypes ?? {}) },
    width: { ...DEFAULT_CONFIG.width, ...(overrides.width ?? {}) },
    processFlowHeader: overrides.processFlowHeader ?? DEFAULT_CONFIG.processFlowHeader,
    cellAlign: { ...DEFAULT_CONFIG.cellAlign, ...(overrides.cellAlign ?? {}) },
    headerAlign: { ...DEFAULT_CONFIG.headerAlign, ...(overrides.headerAlign ?? {}) },
  }
}
