# Generated by Django 5.2.14 on 2026-06-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_master', '0002_remove_stationmaster_addr_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmaster',
            name='purge_target_yn',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='stationmaster',
            name='addr_book_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
