# Generated by Django 5.2.16 on 2026-08-12 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='새 대화', max_length=120)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_conversation',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AssistantContextSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_key', models.CharField(max_length=512)),
                ('kind', models.CharField(default='generic', max_length=64)),
                ('scope', models.JSONField(default=dict)),
                ('coverage', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_snapshots', to='assistant.assistantconversation')),
            ],
            options={
                'db_table': 'assistant_context_snapshot',
            },
        ),
        migrations.CreateModel(
            name='AssistantConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True, default='')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='assistant.assistantconversation')),
            ],
            options={
                'db_table': 'assistant_conversation_summary',
            },
        ),
        migrations.CreateModel(
            name='AssistantGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_request_id', models.CharField(max_length=128)),
                ('context_key', models.CharField(default='assistant', max_length=512)),
                ('status', models.CharField(choices=[('queued', '대기'), ('streaming', '생성 중'), ('completed', '완료'), ('stopped', '중단'), ('failed', '실패')], default='queued', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='assistant.assistantconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_generation',
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('context_key', models.CharField(default='assistant', max_length=512)),
                ('sources', models.JSONField(default=list)),
                ('user_sdwt_prod', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='assistant.assistantcontextsnapshot')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantconversation')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='assistant.assistantgeneration')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assistant.assistantmessage')),
                ('revision_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='assistant.assistantmessage')),
            ],
            options={
                'db_table': 'assistant_message',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='assistantconversation',
            name='current_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assistant.assistantmessage'),
        ),
        migrations.CreateModel(
            name='AssistantMessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('up', '도움됨'), ('down', '도움 안 됨')], max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='assistant.assistantmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_message_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_message_feedback',
            },
        ),
        migrations.AddIndex(
            model_name='assistantcontextsnapshot',
            index=models.Index(fields=['conversation', '-created_at'], name='idx_asst_snap_conv_created'),
        ),
        migrations.AddConstraint(
            model_name='assistantconversationsummary',
            constraint=models.UniqueConstraint(fields=('conversation', 'context_key'), name='uniq_asst_sum_conv_ctx'),
        ),
        migrations.AddIndex(
            model_name='assistantgeneration',
            index=models.Index(fields=['user', '-created_at'], name='idx_asst_gen_user_created'),
        ),
        migrations.AddConstraint(
            model_name='assistantgeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'streaming'))), fields=('user',), name='uniq_asst_gen_user_active'),
        ),
        migrations.AddConstraint(
            model_name='assistantgeneration',
            constraint=models.UniqueConstraint(fields=('user', 'client_request_id'), name='uniq_asst_gen_user_request'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_asst_msg_conv_created'),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'client_id'), name='uniq_asst_msg_conv_client'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', '-updated_at'], name='idx_asst_conv_user_updated'),
        ),
        migrations.AddIndex(
            model_name='assistantmessagefeedback',
            index=models.Index(fields=['user', '-updated_at'], name='idx_asst_feedback_user_upd'),
        ),
    ]
