# Generated by Codex on 2026-06-20

from __future__ import annotations

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RacbList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("c_racb_id", models.TextField()),
                ("o_racb_id", models.TextField(blank=True, null=True)),
                ("gbm", models.TextField(blank=True, null=True)),
                ("line", models.TextField(blank=True, null=True)),
                ("line_id", models.TextField(blank=True, null=True)),
                ("area", models.TextField(blank=True, null=True)),
                ("sdwt_name", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("sub_title", models.TextField(blank=True, null=True)),
                ("fiveone", models.TextField(blank=True, null=True)),
                ("racb_type_cd", models.TextField(blank=True, null=True)),
                ("major_category", models.TextField(blank=True, null=True)),
                ("minor_category", models.TextField(blank=True, null=True)),
                ("eqp_cb", models.TextField()),
                ("prc_groups", models.TextField(blank=True, null=True)),
                ("level_data", models.TextField(blank=True, null=True)),
                ("status_code", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("detail_type_cd", models.TextField(blank=True, null=True)),
                ("change_cd", models.TextField(blank=True, null=True)),
                ("fdc", models.TextField(blank=True, null=True)),
                ("npw", models.TextField(blank=True, null=True)),
                ("metro", models.TextField(blank=True, null=True)),
                ("defect", models.TextField(blank=True, null=True)),
                ("create_date", models.DateTimeField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("user_name", models.TextField(blank=True, null=True)),
                ("create_user", models.TextField(blank=True, null=True)),
                ("update_date", models.DateTimeField()),
                ("update_user", models.TextField(blank=True, null=True)),
                ("sub_area", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
            ],
            options={
                "db_table": "racb_list",
                "indexes": [
                    models.Index(fields=["eqp_cb", "update_date"], name="idx_racb_list_cb_upd"),
                    models.Index(fields=["update_date"], name="idx_racb_list_upd"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("c_racb_id", "eqp_cb"), name="uniq_racb_list_id_cb"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RacbListLoadJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.TextField()),
                ("file_path", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("dry_run", "Dry run"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
            ],
            options={
                "db_table": "racb_list_load_job",
                "indexes": [
                    models.Index(fields=["status"], name="idx_racb_list_lj_sts"),
                    models.Index(fields=["created_at"], name="idx_racb_list_lj_crt"),
                ],
            },
        ),
    ]
