# Generated by Django 5.2.9 on 2025-12-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appstoreapp",
            name="screenshot_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]

