# Generated by Django 5.2.9 on 2025-12-13 23:58

from __future__ import annotations

import re

from django.db import migrations, models


DATA_URL_PATTERN = re.compile(r"^data:(?P<mime>[^;]*);base64,(?P<data>.+)$", re.DOTALL)


def forwards_migrate_screenshot_data_urls(apps, schema_editor) -> None:
    AppStoreApp = apps.get_model("appstore", "AppStoreApp")

    for app in AppStoreApp.objects.exclude(screenshot_url="").iterator():
        raw = app.screenshot_url or ""
        match = DATA_URL_PATTERN.match(raw)
        if not match:
            continue

        mime = match.group("mime") or ""
        data = match.group("data") or ""
        AppStoreApp.objects.filter(pk=app.pk).update(
            screenshot_url="",
            screenshot_base64=data,
            screenshot_mime_type=mime,
        )


def backwards_restore_screenshot_data_urls(apps, schema_editor) -> None:
    AppStoreApp = apps.get_model("appstore", "AppStoreApp")

    for app in AppStoreApp.objects.filter(screenshot_url="", screenshot_base64__gt="").iterator():
        mime = app.screenshot_mime_type or "image/png"
        data_url = f"data:{mime};base64,{app.screenshot_base64}"
        AppStoreApp.objects.filter(pk=app.pk).update(
            screenshot_url=data_url,
            screenshot_base64="",
            screenshot_mime_type="",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("appstore", "0002_appstoreapp_screenshot_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="appstoreapp",
            name="screenshot_base64",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appstoreapp",
            name="screenshot_mime_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(
            forwards_migrate_screenshot_data_urls,
            backwards_restore_screenshot_data_urls,
        ),
    ]

