# Generated by Django 5.2.9 on 2025-12-14 00:00

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appstore", "0003_appstoreapp_screenshot_base64_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="appstorecomment",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="appstorecomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="appstore.appstorecomment",
            ),
        ),
        migrations.AddIndex(
            model_name="appstorecomment",
            index=models.Index(fields=["parent"], name="appstore_comment_parent_idx"),
        ),
        migrations.CreateModel(
            name="AppStoreCommentLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="appstore.appstorecomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appstore_comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "appstore_comment_like",
            },
        ),
        migrations.AddIndex(
            model_name="appstorecommentlike",
            index=models.Index(fields=["user"], name="idx_appstore_cmtlike_user"),
        ),
        migrations.AddIndex(
            model_name="appstorecommentlike",
            index=models.Index(fields=["comment"], name="idx_appstore_cmtlike_comment"),
        ),
        migrations.AddConstraint(
            model_name="appstorecommentlike",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"),
                name="uniq_appstore_cmtlike_cmt_user",
            ),
        ),
    ]
