# Generated by Django 5.2.9 on 2025-12-15 00:00

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appstore", "0004_appstorecomment_replies_and_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="appstoreapp",
            name="screenshot_gallery",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

