# Generated by Django 5.2.14 on 2026-06-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_process_comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctprocesscomment',
            name='update_flag',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
