# Generated by Django 5.2.14 on 2026-06-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_process_comment', '0002_ctprocesscomment_update_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctprocesscomment',
            name='llm_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
