# Generated by Django 5.2.9 on 2025-12-13 05:53

import api.account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('sabun', models.CharField(max_length=50, unique=True)),
                ('knox_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('username_en', models.CharField(blank=True, max_length=150, null=True)),
                ('givenname', models.CharField(blank=True, max_length=150, null=True)),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('deptname', models.CharField(blank=True, max_length=128, null=True)),
                ('deptid', models.CharField(blank=True, max_length=50, null=True)),
                ('grd_name', models.CharField(blank=True, max_length=150, null=True)),
                ('grdname_en', models.CharField(blank=True, max_length=150, null=True)),
                ('busname', models.CharField(blank=True, max_length=150, null=True)),
                ('intcode', models.CharField(blank=True, max_length=64, null=True)),
                ('intname', models.CharField(blank=True, max_length=150, null=True)),
                ('origincomp', models.CharField(blank=True, max_length=150, null=True)),
                ('employeetype', models.CharField(blank=True, max_length=150, null=True)),
                ('x_ms_forwarded_client_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('line', models.CharField(blank=True, max_length=64, null=True)),
                ('user_sdwt_prod', models.CharField(blank=True, max_length=64, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'account_user',
            },
            managers=[
                ('objects', api.account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=128)),
                ('line', models.CharField(max_length=64)),
                ('user_sdwt_prod', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'account_affiliation',
                'indexes': [models.Index(fields=['department'], name='aff_hier_department'), models.Index(fields=['line'], name='aff_hier_line'), models.Index(fields=['user_sdwt_prod'], name='aff_hier_user_sdwt_prod')],
                'unique_together': {('department', 'line', 'user_sdwt_prod')},
            },
        ),
        migrations.CreateModel(
            name='AffiliationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knox_id', models.CharField(db_index=True, max_length=50)),
                ('effective_from', models.DateTimeField()),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('line', models.CharField(blank=True, max_length=64, null=True)),
                ('user_sdwt_prod', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'account_affiliation_history',
                'indexes': [models.Index(fields=['knox_id', 'effective_from'], name='sender_sdwt_effective'), models.Index(fields=['user_sdwt_prod'], name='sender_sdwt_user_sdwt')],
                'unique_together': {('knox_id', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserSdwtProdAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sdwt_prod', models.CharField(max_length=64)),
                ('can_manage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdwt_prod_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdwt_prod_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_sdwt_prod_access',
                'indexes': [models.Index(fields=['user'], name='user_sdwt_access_user'), models.Index(fields=['user_sdwt_prod'], name='user_sdwt_access_prod')],
                'unique_together': {('user', 'user_sdwt_prod')},
            },
        ),
        migrations.CreateModel(
            name='UserSdwtProdChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('line', models.CharField(blank=True, max_length=64, null=True)),
                ('from_user_sdwt_prod', models.CharField(blank=True, max_length=64, null=True)),
                ('to_user_sdwt_prod', models.CharField(max_length=64)),
                ('effective_from', models.DateTimeField()),
                ('applied', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdwt_prod_changes_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdwt_prod_changes_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdwt_prod_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_sdwt_prod_change',
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['user', 'effective_from'], name='user_sdwt_change_eff'), models.Index(fields=['applied'], name='user_sdwt_change_applied')],
            },
        ),
    ]
