apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: etch-sso
resources:
  - stack.yaml
images:
  - name: traefik-internal
    newName: repository.samsungds.net/proxy-docker-registry-1.docker.io/traefik
    newTag: v3.7.1
