// src/app/layout.js
import { Separator } from "@/components/ui/separator"
import { SidebarInset, SidebarTrigger } from "@/components/ui/sidebar"
import { ThemeProvider } from "@/components/theme-provider"
import { ThemeToggle } from "@/components/theme-toggle"
import { DynamicBreadcrumb } from "@/components/navigation/dynamic-breadcrumb"
import { AppSidebar, AppSidebarProvider } from "@/features/navigation"
import { getDistinctLineIds } from "@/features/line-dashboard/api/get-line-ids"
import "./globals.css"
import { Toaster } from "@/components/ui/sonner"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  let lineOptions = []

  try {
    lineOptions = await getDistinctLineIds()
  } catch {
    lineOptions = []
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <AppSidebarProvider>
            <AppSidebar lineOptions={lineOptions} />
            <SidebarInset>
              <header
                className="flex h-14 shrink-0 items-center justify-between gap-2 px-4 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12"
              >
                <div className="flex items-center gap-2">
                  <SidebarTrigger className="-ml-1" />
                  <Separator orientation="vertical" className="mr-2 data-[orientation=vertical]:h-4" />
                  <DynamicBreadcrumb />
                </div>
                <ThemeToggle />
              </header>
              <main className="flex-1 min-h-0 min-w-0 p-2 pt-0 overflow-hidden">
                <div className="h-full overflow-hidden">
                  {children}
                  <Toaster />
                </div>
              </main>
            </SidebarInset>
          </AppSidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
