include:
  - path:
      - airflow.yml
      - airflow.local.yml

services:
  ftp:
    image: fauria/vsftpd
    container_name: datalake-ftp
    environment:
      FTP_USER: ${FTP_USER:-ftpuser}
      FTP_PASS: ${FTP_PASS:-ftp1234}
      PASV_ADDRESS: ${FTP_PASV_ADDRESS:-127.0.0.1}
      PASV_MIN_PORT: ${FTP_PASV_MIN_PORT:-8076}
      PASV_MAX_PORT: ${FTP_PASV_MAX_PORT:-8079}
    ports:
      - "${FTP_PORT:-6380}:21"
      - "${FTP_PASV_MIN_PORT:-8076}-${FTP_PASV_MAX_PORT:-8079}:${FTP_PASV_MIN_PORT:-8076}-${FTP_PASV_MAX_PORT:-8079}"
    volumes:
      - "${DATA_MOVEMENT_HOST_PATH:-../data/data_movement}:/home/vsftpd/${FTP_USER:-ftpuser}/data_movement"
    restart: unless-stopped
    networks:
      shared-net:
        aliases:
          - ftp

networks:
  shared-net:
    external: true
    name: shared-net
