# Generated by Django 5.2.14 on 2026-07-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l3_spider', '0003_l3spidermailrulepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l3spidermailrule',
            name='date_from',
        ),
    ]
