# Generated by Django 5.2.8 on 2025-11-24 03:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSDWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_sdwt_prod', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'line_sdwt',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('line', models.CharField(blank=True, max_length=64, null=True)),
                ('sdwt', models.CharField(blank=True, max_length=64, null=True)),
                ('sabun', models.CharField(blank=True, max_length=64, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'api_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField(default=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneEarlyInformV3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=50)),
                ('main_step', models.CharField(max_length=50)),
                ('custom_end_step', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'drone_early_inform_v3',
                'constraints': [models.UniqueConstraint(fields=('line_id', 'main_step'), name='uniq_line_mainstep')],
            },
        ),
        migrations.CreateModel(
            name='DroneSOPV3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sdwt_prod', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_group', models.CharField(blank=True, max_length=50, null=True)),
                ('eqp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('chamber_ids', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_id', models.CharField(blank=True, max_length=50, null=True)),
                ('proc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ppid', models.CharField(blank=True, max_length=50, null=True)),
                ('main_step', models.CharField(blank=True, max_length=50, null=True)),
                ('metro_current_step', models.CharField(blank=True, max_length=50, null=True)),
                ('metro_steps', models.CharField(blank=True, max_length=100, null=True)),
                ('metro_end_step', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('knoxid', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user_sdwt_prod', models.CharField(blank=True, max_length=50, null=True)),
                ('defect_url', models.TextField(blank=True, null=True)),
                ('send_jira', models.SmallIntegerField(default=0)),
                ('needtosend', models.SmallIntegerField(default=1)),
                ('custom_end_step', models.CharField(blank=True, max_length=50, null=True)),
                ('inform_step', models.CharField(blank=True, max_length=50, null=True)),
                ('jira_key', models.CharField(blank=True, max_length=50, null=True)),
                ('informed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drone_sop_v3',
                'indexes': [models.Index(fields=['send_jira', 'needtosend'], name='send_jira_needtosend'), models.Index(fields=['sdwt_prod'], name='sdwt_prod')],
                'constraints': [models.UniqueConstraint(fields=('line_id', 'eqp_id', 'chamber_ids', 'lot_id', 'main_step'), name='uniq_row')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
