# Generated by Django 5.2.8 on 2025-11-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneearlyinformv3',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='droneearlyinformv3',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
