# Generated by Django 5.2.8 on 2025-11-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_db_timestamp_defaults"),
    ]

    operations = []
