# Generated by Django 5.2.8 on 2025-02-09 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_user_sabun'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('접수', '접수'), ('진행중', '진행중'), ('완료', '완료'), ('반려', '반려')], default='접수', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voc_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voc_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VocReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voc_replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.vocpost')),
            ],
            options={
                'db_table': 'voc_reply',
                'ordering': ['created_at'],
            },
        ),
    ]
