# Generated by Django 5.2.8 on 2025-12-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_create_voc_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronesopv3',
            name='instant_inform',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dronesopv3',
            name='metro_steps',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
