# Generated by Django 5.1 on 2024-12-01 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_dronesopv3_instant_inform_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("received_at", models.DateTimeField()),
                ("subject", models.TextField()),
                ("sender", models.TextField()),
                ("recipient", models.TextField()),
                ("body_text", models.TextField(blank=True)),
                ("body_html_gzip", models.BinaryField(blank=True, null=True)),
                ("rag_doc_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "email",
            },
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(fields=["is_deleted"], name="email_is_deleted_idx"),
        ),
    ]
