# Generated by Django 5.1 on 2025-03-06 00:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_create_email_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="email",
            name="email_is_deleted_idx",
        ),
        migrations.RemoveField(
            model_name="email",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="email",
            name="is_deleted",
        ),
    ]
