# Generated by ChatGPT on 2025-03-?? 00:00
from django.db import migrations, models
import django.utils.timezone


def set_unknown_defaults(apps, schema_editor):
    Email = apps.get_model("api", "Email")
    Email.objects.filter(sender_id__isnull=True).update(sender_id="UNKNOWN")
    Email.objects.filter(department_code__isnull=True).update(department_code="UNKNOWN")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_email_soft_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDepartmentHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_id", models.CharField(db_index=True, max_length=50)),
                ("department_code", models.CharField(max_length=50)),
                ("effective_from", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "user_department_history",
            },
        ),
        migrations.AddIndex(
            model_name="userdepartmenthistory",
            index=models.Index(fields=["employee_id", "effective_from"], name="user_dept_hist_emp_eff"),
        ),
        migrations.AddField(
            model_name="email",
            name="department_code",
            field=models.CharField(db_index=True, default="UNKNOWN", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="email",
            name="sender_id",
            field=models.CharField(db_index=True, default="UNKNOWN", max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(set_unknown_defaults, migrations.RunPython.noop),
    ]
