# Generated by Django 5.2.8 on 2025-12-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_email_department_and_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userdepartmenthistory',
            new_name='user_depart_employe_57624b_idx',
            old_name='user_dept_hist_emp_eff',
        ),
    ]
