apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailwind-local
resources:
  - ../../../deploy/portal/k8s/base
  - ingress.yaml
  - storage.yaml
patches:
  - path: api-local-patch.yaml
  - path: web-local-patch.yaml
  - path: edge-local-patch.yaml
  - path: minio-local-patch.yaml
images:
  - name: portal-api
    newName: tailwind-api
    newTag: k8s-local
  - name: portal-web
    newName: tailwind-web
    newTag: k8s-local
