# Generated by Codex on 2026-06-20

from __future__ import annotations

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EqpStatusChg",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("eqp_cb", models.CharField(max_length=41)),
                ("line_id", models.CharField(blank=True, max_length=8, null=True)),
                ("chg_time", models.DateTimeField()),
                ("eqp_code", models.CharField(blank=True, max_length=20, null=True)),
                ("eqp_mode_type", models.CharField(blank=True, max_length=20, null=True)),
                ("eqp_status_type", models.CharField(blank=True, max_length=10, null=True)),
                ("chg_comment", models.CharField(blank=True, max_length=500, null=True)),
                ("operator_emp_id", models.CharField(blank=True, max_length=25, null=True)),
                ("eqp_event_key", models.DecimalField(decimal_places=0, max_digits=38)),
                ("last_update_time", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
            ],
            options={
                "db_table": "eqp_status_chg",
                "indexes": [
                    models.Index(fields=["eqp_cb", "chg_time"], name="idx_eqp_sts_chg_cb_tm"),
                    models.Index(fields=["chg_time"], name="idx_eqp_sts_chg_tm"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("eqp_event_key",), name="uniq_eqp_sts_chg_evt"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EqpStatusChgLoadJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.TextField()),
                ("file_path", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("dry_run", "Dry run"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
            ],
            options={
                "db_table": "eqp_status_chg_load_job",
                "indexes": [
                    models.Index(fields=["status"], name="idx_eqp_sts_chg_lj_sts"),
                    models.Index(fields=["created_at"], name="idx_eqp_sts_chg_lj_crt"),
                ],
            },
        ),
    ]
